### ISSUE TITLE
Epic: E2E Test Suite

### ISSUE THREAD

**Issue by adamewozniak** [ojo-network/ojo#12]
## Problem Definition

We need an e2e test suite which focuses on oracle prices and running a price feeder, similar to how umee's runs 

- [x] #81
- [x] [E2e for contracts](https://github.com/ojo-network/contracts/issues/4)

---

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned
