### ISSUE TITLE
Epic: Airdrop Module

### ISSUE THREAD

**Issue by adamewozniak** [ojo-network/ojo#121]
## Summary

Airdrop module as designed in [design doc 3
](https://github.com/ojo-network/ojo/pull/117)

- [x] Design doc
- [x] #140
- [x] #160
- [x] #162
- [x] ABCI
- [x] #229
- [x] #221
  - Create genesis airdrop account
  - Claim airdrop
  - Unable to claim airdrop after the expiry block
  - Update params with gov prop
- [x] #220

---

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by zarazan** [comment]
All issues complete, closing
