### ISSUE TITLE
Epic: Oracle V1

### ISSUE THREAD

**Issue by adamewozniak** [ojo-network/ojo#30]
## Summary

This issue will be used to track additional changes to the oracle which will be included in V1

- [x] #43
- [x] #42
- [x] #59
- [x] #50 
- [x] #54
- [x] #44 
- [x] #64 
- [x] #69
- [x] #80
- [x] #84
- [x] #95
- [x] #96
- [x] #105

---

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned
