### ISSUE TITLE
Epic: Oracle V2

### ISSUE THREAD

**Issue by adamewozniak** [ojo-network/ojo#55]
## Problem Definition

Oracle V2 issues we want to include in a post-mainnet world

- [ ] Switch logarithmic rewards -> exponential rewards based on miss counter  
- [ ] Suggested price feeder config registry
- [ ] Miss-counter-based confidence level for assets

---

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned
