### ISSUE TITLE
Epic: Mint Module V1

### ISSUE THREAD

**Issue by adamewozniak** [ojo-network/ojo#60]
## Problem Definition

We need a mint module for additional rewards on top of existing PoS staking rewards

- [ ] Spec

## Proposal

---

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned
